// ═══════════════════════════════════════════════════════════════════
//  MediLink 2.0 — Health Feed (Seed Articles)
// ═══════════════════════════════════════════════════════════════════

export const SEED_ARTICLES = [
  { id: '1', emoji: '🦟', title: 'How to Prevent Dengue This Monsoon', category: 'Prevention', readTime: '4 min', 
    content: 'Dengue cases spike dramatically during India\'s monsoon season (June–September), with mosquitoes breeding in stagnant water. Here are evidence-based prevention steps:\n\n<strong>1. Eliminate Breeding Sites</strong> — Empty all containers with standing water: flower pots, coolers, old tyres, and water tanks. Change water in pet bowls daily.\n\n<strong>2. Personal Protection</strong> — Wear full-sleeve clothing, especially during dawn and dusk when Aedes mosquitoes are most active. Use mosquito nets while sleeping.\n\n<strong>3. Repellents</strong> — Apply DEET-based repellents on exposed skin. Citronella oil is a natural alternative but requires reapplication every 30–60 minutes.\n\n<strong>4. Know the Symptoms</strong> — High fever (104°F), severe headache behind the eyes, joint and muscle pain, nausea, and skin rash appearing 2–5 days after fever onset.\n\n<strong>5. When to Seek Emergency Care</strong> — Bleeding from gums or nose, persistent vomiting, abdominal pain, or sudden drop in platelet count (below 1 lakh) needs immediate hospitalization.\n\n<strong>Myth Busted:</strong> Papaya leaf juice has shown some evidence of improving platelet count, but it is NOT a substitute for medical treatment. Always consult a doctor.' },

  { id: '2', emoji: '🍲', title: 'Dal-Chawal: The Complete Protein Science', category: 'Nutrition', readTime: '5 min', 
    content: 'India\'s staple meal — dal (lentils) and chawal (rice) — is one of the most scientifically balanced food combinations in the world.\n\n<strong>The Science of Complete Proteins</strong>\nProteins are made of amino acids. Rice is low in lysine but rich in methionine. Lentils are the opposite — high in lysine, low in methionine. Together, they form a <em>complete protein</em> with all 9 essential amino acids.\n\n<strong>Nutritional Breakdown (1 serving)</strong>\n• Protein: 12–15g (comparable to an egg)\n• Iron: 3.5mg (20% of daily requirement)\n• Fibre: 8g (supports digestion)\n• B-vitamins: Thiamine, folate, niacin\n\n<strong>How to Maximize Benefits</strong>\n1. Add a squeeze of lemon — Vitamin C increases iron absorption by up to 6x.\n2. Include a small amount of ghee — Fat-soluble vitamins (A, D, E, K) need fat for absorption.\n3. Use whole moong or masoor dal — They retain more nutrients than washed varieties.\n\n<strong>For Diabetics:</strong> Replace white rice with brown rice or add vegetables to slow glycemic response. The fibre in dal already helps regulate blood sugar spikes.\n\nThis humble meal provides better protein quality than many expensive supplements — at a fraction of the cost.' },

  { id: '3', emoji: '🧠', title: 'Managing Exam Stress: Evidence-Based Tips', category: 'Mental', readTime: '5 min', 
    content: 'Academic pressure affects millions of students in India. Here are scientifically-proven strategies to manage exam stress effectively:\n\n<strong>1. The 4-7-8 Breathing Technique</strong>\nInhale through your nose for 4 seconds → Hold for 7 seconds → Exhale through mouth for 8 seconds. This activates the parasympathetic nervous system, reducing cortisol (stress hormone) by up to 25% in just 3 cycles.\n\n<strong>2. Sleep Hygiene is Non-Negotiable</strong>\n• Sleep 7–8 hours minimum. Memory consolidation happens during deep sleep.\n• Avoid screens 1 hour before bed — blue light suppresses melatonin.\n• Maintain consistent sleep and wake times, even on weekends.\n\n<strong>3. The Pomodoro Technique</strong>\nStudy for 25 minutes → Break for 5 minutes. After 4 cycles, take a 15–30 minute break. This prevents mental fatigue and improves retention.\n\n<strong>4. Nutrition for Brain Power</strong>\n• Walnuts contain omega-3 fatty acids that improve cognitive function.\n• Dark chocolate (70%+) enhances blood flow to the brain.\n• Bananas provide quick energy without the crash of sugary snacks.\n\n<strong>5. Exercise is a Study Tool</strong>\nJust 20 minutes of brisk walking before studying increases focus by 30%. Exercise releases BDNF (Brain-Derived Neurotrophic Factor), which literally helps grow new brain cells.\n\n<strong>Warning Signs:</strong> If you experience persistent insomnia, panic attacks, or thoughts of self-harm, please reach out to iCall helpline: 9152987821 or Vandrevala Foundation: 1860-2662-345.' },

  { id: '4', emoji: '💧', title: 'ORS at Home: WHO Recommended Recipe', category: 'First Aid', readTime: '3 min', 
    content: 'Diarrhoea kills over 1 lakh children under 5 in India every year. Most of these deaths are preventable with a simple solution: ORS (Oral Rehydration Solution).\n\n<strong>WHO-Approved Home Recipe</strong>\n• 1 litre of clean, boiled (and cooled) water\n• 6 level teaspoons of sugar (or 2 tablespoons)\n• ½ level teaspoon of salt\n• Mix thoroughly until dissolved\n\n<strong>How to Administer</strong>\n• Children under 2: Give 50–100ml after each loose stool.\n• Children 2–10 years: Give 100–200ml after each loose stool.\n• Adults: Drink as much as needed — typically 200–400ml per episode.\n\n<strong>Important Tips</strong>\n1. Prepare fresh batch every 24 hours — discard unused solution.\n2. Do NOT add more salt than recommended — excess salt is dangerous.\n3. Continue breastfeeding if the child is still nursing.\n4. Resume normal feeding as soon as the child can eat.\n\n<strong>When ORS is NOT Enough (Rush to Hospital)</strong>\n• Blood in stool\n• Unable to drink any fluids\n• Sunken eyes with no tears\n• Very drowsy or unconscious\n• Vomiting everything immediately\n\n<strong>Government Supply:</strong> ORS packets are available FREE at all ASHA workers, PHCs, and government hospitals across India.' },

  { id: '5', emoji: '🤰', title: 'Pregnancy Nutrition: Iron-Rich Indian Foods', category: 'Nutrition', readTime: '6 min', 
    content: 'Iron deficiency anaemia affects nearly 50% of pregnant women in India. During pregnancy, blood volume increases by 50%, making iron crucial for both mother and baby.\n\n<strong>Top Iron-Rich Indian Foods (per 100g)</strong>\n• Jaggery (Gur): 11mg iron — Add to milk or make til-gur laddoo.\n• Spinach (Palak): 2.7mg iron — Best cooked with tomatoes (vitamin C).\n• Beetroot (Chukandar): 0.8mg iron + folic acid — Juice or salad.\n• Pomegranate (Anaar): Rich in iron + Vitamin C — Eat daily.\n• Sesame Seeds (Til): 14.5mg iron — Make til chutney or laddoo.\n• Moringa (Drumstick) Leaves: 28mg iron — Add to dal or sambar.\n\n<strong>Iron Absorption Boosters</strong>\n• Vitamin C: Amla, orange, lemon — increases absorption by 6x.\n• Cooking in iron kadhai increases food\'s iron content by 16%.\n\n<strong>Iron Absorption Blockers (Avoid with meals)</strong>\n• Tea and coffee — tannins block iron absorption by 60%.\n• Dairy products — calcium competes with iron. Take calcium supplements at night.\n\n<strong>Recommended Daily Intake</strong>\n• Pregnant women: 35mg/day (ICMR recommendation)\n• Take iron-folic acid (IFA) tablets as prescribed — available free at government hospitals.\n\n<strong>Warning:</strong> Never self-prescribe iron supplements. Excess iron can be toxic. Always consult your gynaecologist.' },

  { id: '6', emoji: '🦷', title: 'Dental Care: Neem Datun vs Modern Toothbrush', category: 'General', readTime: '4 min', 
    content: 'The debate between traditional neem datun (twig) and modern toothbrush has scientific evidence on both sides.\n\n<strong>Neem Datun: The Science</strong>\n• Contains nimbidin and azadirachtin — proven antibacterial compounds.\n• Studies show neem reduces plaque by 36% and gingivitis by 23%.\n• The fibrous bristles naturally clean between teeth.\n• No toothpaste needed — saves money for rural families.\n• Biodegradable — zero waste.\n\n<strong>Modern Toothbrush: The Advantages</strong>\n• Standardized bristle softness prevents gum damage.\n• Reaches all areas including back molars more effectively.\n• Can be paired with fluoride toothpaste for cavity prevention.\n• Electric variants are clinically proven to remove 21% more plaque.\n\n<strong>The Verdict</strong>\nBoth are effective IF used with proper technique:\n1. Brush for a full 2 minutes (most people brush only 45 seconds).\n2. Use gentle circular motions — NOT aggressive horizontal scrubbing.\n3. Replace toothbrush every 3 months (or when bristles splay).\n4. Brush your tongue — it harbours 50% of mouth bacteria.\n\n<strong>Most Important:</strong> Regardless of your tool, visit a dentist every 6 months. Free dental checkups are available at government dental colleges.' },

  { id: '7', emoji: '💉', title: 'Complete Vaccination Schedule for Children', category: 'Prevention', readTime: '7 min', 
    content: 'India\'s Universal Immunization Programme (UIP) is one of the world\'s largest public health programs, providing FREE vaccines to every child.\n\n<strong>Birth</strong>\n• BCG (Tuberculosis) — Left upper arm, leaves a scar.\n• OPV-0 (Polio) — Oral drops.\n• Hepatitis B — Birth dose, within 24 hours.\n\n<strong>6 Weeks</strong>\n• OPV-1 + IPV-1 (Polio)\n• Pentavalent-1 (Diphtheria, Pertussis, Tetanus, Hepatitis B, Hib)\n• Rotavirus-1 (Diarrhoea) — Oral drops\n• PCV-1 (Pneumonia)\n\n<strong>10 Weeks</strong>\n• OPV-2, Pentavalent-2, Rotavirus-2\n\n<strong>14 Weeks</strong>\n• OPV-3 + IPV-2, Pentavalent-3, Rotavirus-3, PCV-2\n\n<strong>9 Months</strong>\n• MR-1 (Measles-Rubella) — Very important\n• JE-1 (Japanese Encephalitis) — in endemic areas\n• PCV Booster\n\n<strong>16–24 Months</strong>\n• MR-2, DPT Booster-1, OPV Booster, JE-2\n\n<strong>5–6 Years</strong>\n• DPT Booster-2\n\n<strong>10 Years</strong>\n• Td (Tetanus-diphtheria)\n\n<strong>Where to Get Vaccinated:</strong> All Primary Health Centres (PHC), Community Health Centres (CHC), government hospitals, and during outreach sessions by ASHA workers. Carry the Mother and Child Protection (MCP) card for tracking.\n\n<strong>Myth:</strong> "Vaccines cause autism" — This has been thoroughly debunked by hundreds of studies involving millions of children.' },

  { id: '8', emoji: '🏃', title: 'Morning Walk Benefits: 30 Minutes That Change Everything', category: 'Fitness', readTime: '4 min', 
    content: 'A simple 30-minute daily morning walk is one of the most powerful health interventions available — and it\'s completely free.\n\n<strong>Proven Benefits (Research-Backed)</strong>\n1. <strong>Heart Health:</strong> Reduces cardiovascular disease risk by 35% (American Heart Association).\n2. <strong>Diabetes Control:</strong> Post-meal walking reduces blood sugar by 30% in Type 2 diabetics.\n3. <strong>Weight Management:</strong> Burns 150–200 calories per 30-minute brisk walk.\n4. <strong>Bone Strength:</strong> Weight-bearing exercise increases bone density, preventing osteoporosis.\n5. <strong>Mental Health:</strong> Walking in nature reduces cortisol by 16% and symptoms of depression by 30%.\n6. <strong>Sleep Quality:</strong> Morning walkers fall asleep 13 minutes faster and sleep 40 minutes longer.\n7. <strong>Immunity:</strong> Regular walkers have 43% fewer sick days per year.\n\n<strong>How to Walk Effectively</strong>\n• Maintain a brisk pace — you should be able to talk but not sing.\n• Swing your arms naturally for balance and calorie burn.\n• Wear comfortable, supportive shoes.\n• Start with 15 minutes if you\'re a beginner, increase gradually.\n\n<strong>Best Time:</strong> 6:00–7:30 AM — Morning sunlight exposure sets your circadian rhythm, boosts Vitamin D production, and improves mood throughout the day.\n\n<strong>For Diabetics:</strong> A 10-minute walk after each meal is more effective at controlling blood sugar than a single 30-minute walk.' },

  { id: '9', emoji: '🌿', title: 'Tulsi, Haldi, Giloy: What Modern Science Says', category: 'Ayurveda', readTime: '6 min', 
    content: 'Traditional Indian herbs have been used for thousands of years. Modern research is now validating many of these ancient practices.\n\n<strong>Tulsi (Holy Basil) — Ocimum tenuiflorum</strong>\n• Contains eugenol, rosmarinic acid, and ursolic acid.\n• <em>Published evidence:</em> Reduces stress (cortisol) by 39% in 6-week randomized trial (Journal of Ayurveda, 2017).\n• Immune-modulating properties — increases NK cell activity.\n• <strong>How to use:</strong> 5–7 fresh leaves daily, or tulsi tea twice daily.\n\n<strong>Haldi (Turmeric) — Curcuma longa</strong>\n• Active compound: Curcumin (3–5% of turmeric powder).\n• <em>Published evidence:</em> Anti-inflammatory effect comparable to ibuprofen for osteoarthritis (Phytotherapy Research, 2014).\n• Enhances liver detoxification pathways.\n• <strong>How to use:</strong> ½ teaspoon with warm milk + a pinch of black pepper (piperine increases curcumin absorption by 2000%).\n\n<strong>Giloy (Guduchi) — Tinospora cordifolia</strong>\n• Contains berberine, tinosporin, and giloin.\n• <em>Published evidence:</em> Reduces fever duration by 2 days in dengue patients (Indian Journal of Medical Research, 2019).\n• Immunomodulatory — increases macrophage activity.\n• <strong>How to use:</strong> Giloy juice (20ml) or giloy-amla juice daily.\n\n<strong>Important Cautions</strong>\n• Giloy can lower blood sugar — diabetics should monitor levels carefully.\n• Turmeric in large amounts may interact with blood thinners.\n• Always inform your doctor about herbal supplements you are taking.\n• These are COMPLEMENTARY to modern medicine, not replacements.' },
];

export async function getPersonalizedFeed(uid, profile) {
  console.log("🔵 [getPersonalizedFeed] called with:", {uid});
  return SEED_ARTICLES;
}

export async function getArticlesByCategory(category) {
  console.log("🔵 [getArticlesByCategory] called with:", category);
  return SEED_ARTICLES.filter(a => a.category === category);
}

export async function readArticle(uid, articleId) {
  console.log("🔵 [readArticle] called with:", {uid, articleId});
}
